### PR TITLE
Make it pretty

### PR DESCRIPTION
**Pull request by indiesquidge**
So we are almost there, guys. I got all three visuals to work on one page, which was such a bitch since a few of us used similar variable names, which created aliases that I had to go and check one by one. But now they are all on one page.

The next step is to make this the correct size for the big screen. I have included a mock .jpg file (and the .psd file so that you can play around with it if you have Photoshop) of what I think would look awesome. The problem I am running into is getting the damn svg elements to play nicely with the rest of css and Bootstrap.

It's 4am now, and I'm still in the lobby; I'm about to die. If any of you can please work on getting the page more presentable, that would be very helpful. I have class until 4pm tomorrow and won't be able to work very much on this before we have to present.

PS – I wouldn't merge this into Master just yet. The code and everything works fine, but I'd rather get the design correct before we push it to master and have it running on the server.

PSS – We also need to change the axes on the live noise graph.

### CODE REVIEW

**Comment by jakecharland** [comment]
Hey team I just worked on the visual stuff austin was talking about above. Just pull the latest on make-it-pretty and you should see my changes. Let me know what you think and give me your suggestions!

**Comment by nfejes** [comment]
I changed the fonts and some minor stuff as well. Dawson, are you at home?
You need to be on the schools network for it to pull data from the Pi's
websocket.

**Comment by indiesquidge** [comment]
Cleaned up the axes on some of the graphs and tweaked a few other things, and I think this is _almost_ ready to ship! The only reason I say almost is because it isn't optimized for the screen resolution of the big screen in the lobby, which is 1920x1080 (huge!). To test for this, open up the the Chrome inspector and just to the right of the magnifying glass (search tool) you'll see a little phone icon. Click on this, and set the dimensions in the top left to 1920x1080. We need to get it looking beautiful on those dimensions before we push it to the server and through it on the main screen for tonight's showing. 

I will be in the lobby at 4pm, but I have class until then. If anyone else has free time, create a new branch and try to make it work for that size. Awesome job everyone :+1:

**Comment by indiesquidge** [comment]
I am currently working on fixing the merge conflicts between master and make-it-pretty, so don't worry about that. I'll get this branch merged soon.

**Comment by antsankov** [comment]
This sounds fantastic guys! I'll be there at 4:15ish as well to make sure
everything is working well on the server end.

**Pull request merged**
